# Use the README file as a reference to customize settings.

Paint:
  fields:
    default: userid, category, title, filedata
    form: userid, category, title, filedata
  relationships: 
  application: Application
